### ISSUE TITLE
Build/polish your Resume

### ISSUE THREAD

**Issue by santiagobasulto** [rmotr-career-services/career-services-Berelarsenp#12]
Resumes have changed a lot in the past years and can really help or hurt the impression you are making depending on how much time you have put into it. Check out some of the links below to follow ways to make sure yours fit modern standards. 

Some good tips on what people look for on resumes today:
https://www.themuse.com/advice/43-resume-tips-that-will-help-you-get-hired

Do's and dont's of a modern resume:
https://www.reddit.com/r/EngineeringStudents/comments/2pvcmy/guide_to_resume_writing_with_examples/

**Deliverable:** Once you're done. Upload your resume **in PDF format** to the shared Google Drive directory (provided by RMOTR) with the following name structure: `{first_name}-{last_name}-resume.pdf`. Don't forget to close the issue for review.

`RMOTR: PB#1`

**Comment by jasonmeeks** [comment]
Very visually pleasing resume! 

Some suggestions:
- spelling error for the month for free code camp (check for others as well, spanish isnt my native language haha)
- For some of your education and work, try and talk about big projects you did. tangible things you accomplished. If you just say "I learned django" it's not descriptive of HOW MUCH django you know and your capability with it

Otherwise great job!!!
