### ISSUE TITLE
Come Up with 3 Blog Posts ideas

### ISSUE THREAD

**Issue by santiagobasulto** [rmotr-career-services/career-services-Berelarsenp#16]
This is another way to show you are active in the programming world. Find something you are interested in, do some research about it, and share your findings! People tend to appreciate articles they find something new and useful from.

**Deliverable:** Come up with 3 ideas of posts to write in the following weeks. Post them as a comment in this issue and close it for review.

`RMOTR: PB#8`

**Comment by Berelarsenp** [comment]
IDEAS! (Will be medium posts, someday soon)

1) Write about my Demo Day Project. the process, how I learn things while trying and doing, and a conclusion about it.
2) I want to give a talk about Jupyter Notebooks this year, so it would be amazing to have a post about it that helps me organize a clarify ideas.
3) Write about my personal experience since I started my career in IT. The fact that I'm a non-male person, how that has affected my learning process and my decision to study this and what I've done and continue doing to overcome the issues related. This is more like a personal post, but since it took me 10 years to assume that I liked science and programming and understand that careers and professions have no gender, it'll be destined to encourage other non-male persons that may be going through something similar.
