### ISSUE TITLE
Pick a project idea

### ISSUE THREAD

**Issue by santiagobasulto** [rmotr-career-services/career-services-Berelarsenp#7]
It is recommended that you come up with at least 3 ideas for your project and then choose the one you like the best and seems the most technically feasible.

**Deliverable**: Once you have selected your project idea, write the idea and why you chose it in this issue and close it for review.

`RMOTR: DD#2`

**Comment by Berelarsenp** [comment]
Femicides in Argentina: looking for behavioral patterns

Between January the 1st and December 31 of 2017, and according to Observatory of Violence Against Women “Not One [Woman] Less” (“Ni Una Menos”) belonging to MuMaLá, a total of 298 femicides were registered in Argentina. In the absence of official statistics on femicides in Argentina, the Civil Association La Casa del Encuentro produces in 2008 the first report of femicides in Argentina.
Lavaca, an alternative media cooperative, takes the data generated by La Casa del Encuentro to start another femicides database, with its first records dated in 1974. It aims to be a transparent and focused on the victim.

There is also an official database of the Supreme Court of Justice of the Nation with records of femicides since 2012. This database includes transvesticides and it says if the killed person is the final victim of the femicide or a relative/friend. 

There are two behaviors that catch my attention: the first is the one described before, the killing of a relative/friend of the final victim in order to control and torment her; the other one is the suicide of the femicide after having killed his victim. Both behaviors respond to a way of demonstrate their power and to make clear they “own” those women, so they can decide what to do with their lives. I have reasons to think that there are also some behaviors related to period of the month and year or payment date, for example, so I hope to get some favorable result from the analysis of the databases.

The final idea is to write about the process and make some convincing conclusions illustrated with interesting graphics like this study.
