### ISSUE TITLE
Investigate meetups and events to attend in the following weeks

### ISSUE THREAD

**Issue by santiagobasulto** [rmotr-career-services/career-services-Berelarsenp#9]
The best way to get a job is by knowing someone. Attending networking events and making solid connections with people can really aid your job hunt. Be genuine and memorable.

You can find networking events by googling for them in your area. Try and focus on programming/technical events where possible. https://www.meetup.com/ is a great place to find events as well. Startup week, startupweekend and events like those are also cool if you have one in your city.

**Deliverable:** Research future events and post at least 3 events you would like to attend in the following month. Post them as a comment and as you attend them, briefly write your takeaways from each event as a comment as well.

`RMOTR: PB#7`

**Comment by Berelarsenp** [comment]
11/5 - Birras AFK. An invitation from Interdimensional Pirate Party ([Partido Interdimensional Pirata](https://partidopirata.com.ar/)) to a meeting in which we will drink beer and meet people Away From Keyboard. This group is not a political party in terms of government like in many countries, but promotes self-training in security, surveillance and cyber-activism.

12/5 - [PyDay La Plata](https://pydaylp.python.org.ar/#/). An entire day of Python talks. There's a chance that I give an Introduction to Python talk with Andrés Delfino. I'm going to take part with LinuxChix in a talk about gender diversity too.

18/5 - [Meetup LaplataJS](https://www.eventbrite.com.ar/e/laplatajs-meetup-185-tickets-45689467427). I usually attend to LaplataJS meetups, not because I understand about JS, but because of the people, who are the ones who encouraged me to gen involved in IT. 

??/5 - [Meetup R-LadiesLP](https://www.facebook.com/RLadiesLP/). It's a new community in our city and they're planning their 2nd meeting.

??/5 - [LinuxChixLP meeting](https://www.facebook.com/LinuxChixLP/). We're planning to start a new event format in which we can learn programming concepts and improve our skills as Linux Operators, inviting a small amount of people who might be interested on any topic.

**Comment by Berelarsenp** [comment]
11/5 - Birras AFK
It was a great night! We met at a beerhouse, so obviously we had beer and ate pizza. Pirate's are amazing people, committed to cyber-hacktivism and feminism aswell. One of the guys, show us a project he has with other people, a portable library. It was made whit a Raspberry Pi and a portable charger. Aside form that, we'd like to join again and start working on something together... We'll find out in the next chapter!

**Comment by Berelarsenp** [comment]
12/5 - PyDayLP
Such a long day! Finally, I gave the Introduction to programming with Python talk with Andrés. It was one of the first talks of the day, was my first technical talk and I wasn't nervous at all... I enjoyed it a lot! I had spoken in front of many people before several times, but in gender debates or accompanied by my colleagues from LinuxChix, and I know that it's difficult for women to speak up in front of people, because people judge us all the time by the mere fact of being a woman. So this is like a little big victory for me.
The majority of the talks were designed for people with more knowledge than me, but I enjoyed them. I learned how to find which satellites could be watching me, and how to use logs for debugging or have control.
Also, organizers gave me an official t-shirt and a free lunch because I was a speaker :smile:

**Comment by Berelarsenp** [comment]
18/5 - Meetup LaplataJS
It was a great meetup! The guys are worried about the lack of women in the community, so they're putting into action. They presented a CoC they've made in the last month, and took some minutes to discuss about that, and the importance of having women and guarantee them a safety space. They've also invited two women to be the speakers of the evening, so they're doing an amazing work.
It also was the 4th anniversary of their community, so MercadoLibre gave away a catering for all the people, nomnomnom!
I talked with a few friends, and came up with some big ideas and projects for near future, like 3 talk ideas (and Medium posts too!), and joining an amazing project called [livecoding](https://en.wikipedia.org/wiki/Live_coding), in which people make live music by coding

**Comment by Berelarsenp** [comment]
Meetup R-LadiesLP and LinuxChixLP meeting
Neither of us has a date for our meetups, so I'll go to this events whenever they happen :)

**Comment by jasonmeeks** [comment]
Thanks for being so thorough with this! Amazing!
